### ISSUE TITLE
Problems creating table

### ISSUE THREAD

**Issue by ChayaSt** [choderalab/torsionfit#14]
After changing ```tables.parameters.MAX_COLUMNS``` I stop getting the warning but still get this error

```
Traceback (most recent call last):
  File "example.py", line 33, in <module>
    sampler.sample(iter=10000)
  File "/home/chayas/anaconda/lib/python2.7/site-packages/pymc/MCMC.py", line 277, in sample
    Sampler.sample(self, iter, length, verbose)
  File "/home/chayas/anaconda/lib/python2.7/site-packages/pymc/Model.py", line 243, in sample
    self.db._initialize(self._funs_to_tally, length)
  File "/home/chayas/anaconda/lib/python2.7/site-packages/pymc/database/hdf5.py", line 444, in _initialize
    expectedrows=length)
  File "/home/chayas/anaconda/lib/python2.7/site-packages/tables/file.py", line 1067, in create_table
    chunkshape=chunkshape, byteorder=byteorder)
  File "/home/chayas/anaconda/lib/python2.7/site-packages/tables/table.py", line 867, in __init__
    byteorder, _log)
  File "/home/chayas/anaconda/lib/python2.7/site-packages/tables/leaf.py", line 262, in __init__
    super(Leaf, self).__init__(parentnode, name, _log)
  File "/home/chayas/anaconda/lib/python2.7/site-packages/tables/node.py", line 269, in __init__
    self._v_objectid = self._g_create()
  File "/home/chayas/anaconda/lib/python2.7/site-packages/tables/table.py", line 1019, in _g_create
    self._v_new_title, self.filters.complib or '', obversion)
  File "tableextension.pyx", line 212, in tables.tableextension.Table._create_table (tables/tableextension.c:3079)
tables.exceptions.HDF5ExtError: Problems creating the table
Closing remaining open files:fragments.db.hdf5...done
```

**Comment by jchodera** [comment]
That's odd.  If you reduce the number of iterations, does that change the error?
```python
sampler.sample(iter=10)
```

**Comment by jchodera** [comment]
Can you paste the whole thing including the warning?

**Comment by jchodera** [comment]
[This issue](https://github.com/pymc-devs/pymc/issues/56) suggests you set `trace=False` for variables you define but won't need traces for.  For example, you might not need the traces for the `mm_energy` deterministic parameters.

**Comment by jchodera** [comment]
It may be possible to just try a different backend, like the text file backend.  This may not be as high-performance, but might work for now.

**Comment by ChayaSt** [comment]
setting ```trace=False``` to ```mm_energy``` didn't solve the problem. All other parameters are needed. I'm running it with the text file backend for now. It's running but slow.

**Comment by jchodera** [comment]
This is wacky.  I guess we will have to write a NetCDF4 backend for this.

**Comment by ChayaSt** [comment]
NetcDF4 backend written. Closing this issue.
