### ISSUE TITLE
travis error

### ISSUE THREAD

**Issue by jchodera** [choderalab/torsionfit#27]
I can reproduce this failure on my machine:
```
======================================================================
ERROR: Failure: ValueError (zero-size array to reduction operation minimum which has no identity)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/choderaj/miniconda/envs/_test/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/choderaj/miniconda/envs/_test/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/choderaj/miniconda/envs/_test/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/choderaj/miniconda/envs/_test/lib/python2.7/site-packages/torsionfit/tests/test_torsionFitModel.py", line 30, in <module>
    model = TorsionFitModel(param, stream, frag, platform=platform)
  File "/Users/choderaj/miniconda/envs/_test/lib/python2.7/site-packages/torsionfit/TorsionFitModel.py", line 101, in __init__
    def mm_energy(pymc_parameters=self.pymc_parameters, param=param):
  File "/Users/choderaj/miniconda/envs/_test/lib/python2.7/site-packages/pymc/InstantiationDecorators.py", line 250, in deterministic
    return instantiate_n(__func__)
  File "/Users/choderaj/miniconda/envs/_test/lib/python2.7/site-packages/pymc/InstantiationDecorators.py", line 243, in instantiate_n
    return Deterministic(parents=parents, **kwds)
  File "/Users/choderaj/miniconda/envs/_test/lib/python2.7/site-packages/pymc/PyMCObjects.py", line 442, in __init__
    verbose=verbose)
  File "/Users/choderaj/miniconda/envs/_test/lib/python2.7/site-packages/pymc/Node.py", line 219, in __init__
    Node.__init__(self, doc, name, parents, cache_depth, verbose=verbose)
  File "/Users/choderaj/miniconda/envs/_test/lib/python2.7/site-packages/pymc/Node.py", line 129, in __init__
    self.parents = parents
  File "/Users/choderaj/miniconda/envs/_test/lib/python2.7/site-packages/pymc/Node.py", line 152, in _set_parents
    self.gen_lazy_function()
  File "/Users/choderaj/miniconda/envs/_test/lib/python2.7/site-packages/pymc/PyMCObjects.py", line 453, in gen_lazy_function
    self._value.force_compute()
  File "LazyFunction.pyx", line 257, in pymc.LazyFunction.LazyFunction.force_compute (pymc/LazyFunction.c:2409)
  File "/Users/choderaj/miniconda/envs/_test/lib/python2.7/site-packages/torsionfit/TorsionFitModel.py", line 106, in mm_energy
    platform=self.platform)
  File "/Users/choderaj/miniconda/envs/_test/lib/python2.7/site-packages/torsionfit/TorsionScanSet.py", line 252, in compute_energy
    self.mm_energy -= self.mm_energy.min() + Quantity(value=float(offset.value), unit=kilojoules_per_mole)
  File "/Users/choderaj/miniconda/envs/_test/lib/python2.7/site-packages/simtk/unit/quantity.py", line 560, in min
    mymin = self._value.min(*args, **kwargs)
  File "/Users/choderaj/miniconda/envs/_test/lib/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity

----------------------------------------------------------------------
```

**Comment by ChayaSt** [comment]
Do you get this error after normal installation with setup.py?

**Comment by jchodera** [comment]
The issue seems to be with this line:
```
  File "/Users/choderaj/miniconda/envs/_test/lib/python2.7/site-packages/torsionfit/TorsionScanSet.py", line 252, in compute_energy
    self.mm_energy -= self.mm_energy.min() + Quantity(value=float(offset.value), unit=kilojoules_per_mole)
```
It could be that there is a weird `numpy/simtk.unit.Quantity` issue with the `.min()` operation.  Is `self.mm_energy` a `Quantity` wrapping `numpy` array?

**Comment by jchodera** [comment]
I did `conda build devtools/conda-recipe` to replicate what is done on travis.

**Comment by ChayaSt** [comment]
> It could be that there is a weird numpy/simtk.unit.Quantity issue with the .min() operation. Is self.mm_energy a Quantity wrapping numpy array?

That can be. Maybe we can change this too ```self.mm_energy._value``` for the ```numpy``` array without the ```Quantity``` wrapper?

**Comment by jchodera** [comment]
> That can be. Maybe we can change this too self.mm_energy._value for the numpy array without the Quantity wrapper?

It's best to *never* access the value without converting to units first.  It's much better to pick a standard unit and explicitly convert to that:
```python
energy_unit = unit.kilocalories_per_mole
self.mm_energy -= unit.Quantity((self.mm_energy / energy_unit).min() + (offset/energy_unit), energy_unit)
```
but we really shouldn't need to be doing all of those weird conversions.  It *should* "just work" unless there is a bug in `simtk.unit`.

**Comment by ChayaSt** [comment]
> but we really shouldn't need to be doing all of those weird conversions. It should "just work" unless there is a bug in simtk.unit.

Yeah. The version of OpenMM that I'm using is 6.3 and I don't get this failure. What's the version of OpenMM you got with ```conda build devtools/conda-recipe```

**Comment by jchodera** [comment]
You can see my changes to the conda dev recipe here: https://github.com/choderalab/torsionfit/pull/28

**Comment by ChayaSt** [comment]
Closing. Resolved with https://github.com/choderalab/torsionfit/pull/29
